### ISSUE TITLE
[Feature Request] Add WARNING-only command line

### ISSUE THREAD

**Issue by glerouxlandr** [andrebrait/1g1r-romset-generator#11]
For the sake of helping users with incomplete sets, instead of parsing the whole output to check for each warnings, may I suggest the addition of the either:
- Adding a "--only-warning" command line to hide the OK output;
- or adding a text file output for errors and warning, to check later on.

**Comment by andrebrait** [comment]
Yeah, that was a consequence of me being a Linux-only user. It's pretty natural to me to run `command 2>stderr.txt` to get the separate error messages. Indeed, what you said is better, I think.

I'm going to add that. Basically, I'll redirect whatever was going to `sys.stderr` to this file, if the option is set.

**Comment by andrebrait** [comment]
I did something, though not an option anymore.

Other than fatal or critical stuff, I'm outputting all warnings to a log file called `generate.log` and telling the user to check it after the execution ends.

Would that be enough for you? :-)

**Comment by glerouxlandr** [comment]
It's great! Thank you for your work :)

**Comment by andrebrait** [comment]
May I close this then? :)
