### ISSUE TITLE
Hash checking might not work with NES ROMs. Handle Header information and check sums properly

### ISSUE THREAD

**Issue by andrebrait** [andrebrait/1g1r-romset-generator#12]
This is actually just a reminder for myself. Might generate a new version.

**Comment by glerouxlandr** [comment]
Is it the same problem for FDS games?

**Comment by andrebrait** [comment]
Likely yes, but it should be fixed in 1.7.1 now. Do you have any issues with FDS?

**Comment by glerouxlandr** [comment]
Indeed, even with 1.7.1, tested now, no FDS roms seems to pass. NES works like a charm however :)

**Comment by andrebrait** [comment]
Hmm... Reopening this then. I need to check FDS then

**Comment by andrebrait** [comment]
@glerouxlandr could you download the latest version from master and see if it works for FDS? It should, but I'll implement full support for header files later on

**Comment by glerouxlandr** [comment]
@andrebrait It seems to work allright 👍 Well done! This is a very useful tool

**Comment by andrebrait** [comment]
@glerouxlandr I gave it a try with FDS and it works well. Could you please try using 1.8.0 and seeing if it works for you for the NES and FDS?
