### ISSUE TITLE
No module named 'distutils.util'

### ISSUE THREAD

**Issue by dani763f** [andrebrait/1g1r-romset-generator#18]
Trying to run the script i get the following error:
```
$ python3 generate.py                       
Traceback (most recent call last):                                                                                        
File "generate.py", line 15, in <module>                                                                                  
from modules import datafile, header                                                                                  
File "pathremovedforprivacy/header.py", line 3, in <module>                                 
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'

```

This happens no matter what i try. python3 generate.py --version returns the same.

1.7.0 works fine, but anything newer doesn't. Tested on both a debian install and on WSL on windows 10 (where 1.7.0 works fine). Am i just missing something obvious? Also tried extracting to a new directory just to test that i did not mix the different versions of the script.

Any help is appreciated :)

**Comment by andrebrait** [comment]
Ah, yes. Maybe that's not installed by default on every distro out there.

I'm gonna remove the dependency and just make my own parser then.

**Comment by dani763f** [comment]
Thanks for the info, and for making such and awesome tool available! 🙂

**Comment by andrebrait** [comment]
Thanks, and sorry for breaking it. I really try hard not to :/

I'll take care of it this weekend

**Comment by dani763f** [comment]
No stress :) Take your time! Change management sure is the no. 1 enemy of IT in general :P

**Comment by andrebrait** [comment]
This should be resolved if you download the files from this repository now
Let me know if it somehow still doesn't work for you

**Comment by dani763f** [comment]
Confirmed working :)
