### ISSUE TITLE
ROMs with no language specified are always skipped

### ISSUE THREAD

**Issue by CebolaBros64** [andrebrait/1g1r-romset-generator#22]
ROMs with no language specified in filename are skipped regardless of the inclusion of the -l argument
Take for example, the complete Family Disk System romset. Using the following arguments:
```powershell
python generate.py -r "JP" -l "en, jp" --all-regions-with-lang -d "@ dats/Nintendo - Family 
Computer Disk System (FDS) (Parent-Clone) (Parent-Clone) (20200310-115017).dat" -i "@ 
roms/Nintendo - Family Computer Disk System (FDS) (20200310-115017)" --no-all --no-unlicensed `
-o "! output/fdsc"
```
I only got the following ROMs as output:
```
Clu Clu Land (Japan) (En) (Disk Writer) [b].zip
Pro Wres (Japan) (En).zip
Vs. Excitebike (Japan) (En).zip
```
Omitting the -l argument outputs no ROMs.

**Comment by andrebrait** [comment]
Hm, weird. It shouldn't be this way. I'll look into it

**Comment by andrebrait** [comment]
Well, actually, what's happening here is that:

1. The correct region for Japan is `JPN`, not `JP`
2. The list of languages does not handle spaces, so the languages you're providing are actually `en` and ` jp`, with a space in front of it.

Yes, I should be parsing that better :-(

**Comment by andrebrait** [comment]
@CebolaBros64 did you get it to work after all?

**Comment by CebolaBros64** [comment]
Yes, actually! Sorry for not answering beforehand. Changing the region from JP to JPN was enough to make it work here
