### ISSUE TITLE
Extensions Cannot Be Used when Scanning

### ISSUE THREAD

**Issue by Seratai** [andrebrait/1g1r-romset-generator#25]
Hi,

I am having a hard time getting the generator to work properly.  The error I am receiving says "extensions cannot be used when scanning"

The input folder has 2 files, Megaman Europe and Megaman USA. I am trying to generate a USA collection. Both files are unzipped and in the folder as a .nes file.

The script I am running is:
python3 generate.py -r USA -l en -e zip --no-all --all-regions-with-lang -d "Nintendo - Nintendo Entertainment System (Parent-Clone) (20200506-060331).dat" -i "/media/pi/Seagate Backup Plus Drive/Games/ROMS/No Intro Start Up/NES Test" -o "/media/pi/Seagate Backup Plus Drive/Games/ROMS/No Intro Start Up 1G1R USA EUR English/NES Test"

I am not sure why I am receiving the error message. I tried trouble shooting by unzipping the files from their individual .zip format. On a secondary note, is this tool able to be run without extracting the files?

**Comment by andrebrait** [comment]
Well, as the message says, you're getting the error because you're passing the option ,`-e zip` to use the `zip` extension, while in the scanner mode. Remove it from your command ;-)

And yes, it works with zipped files as well. No need to extract them.

**Comment by pcone** [comment]
It does look like the example input on the wiki page contains -e zip while not specifying --no-scan, this might be the source of the confusion?

https://github.com/andrebrait/1g1r-romset-generator/wiki/Generating-the-1G1R-set

**Comment by andrebrait** [comment]
Yes, I realize the documentation is outdated. I have to update it :-/

**Comment by andrebrait** [comment]
Closing this as I have updated the documentation.
