### ISSUE TITLE
Unzipped ROM files will create a parent folder

### ISSUE THREAD

**Issue by Stoneman71** [andrebrait/1g1r-romset-generator#28]
I have all my genesis roms unzipped in one folder. When I execute the generator, it creates for each .md file a folder within the .md rom file. I may go around this with: -e md --no-scan, or I think it will work when I use a zipped rom set.

Is it possible to scan the unzipped rom set and then no creation of a parent folder?

**Comment by andrebrait** [comment]
Someone sent me an email the other day. It seems I screwed that up in the last update. I'll try to fix it soon.

The successor to this tool will be much, much more properly tested.
