### ISSUE TITLE
--exclude-after "file:exclude-after.txt" and --exclude "file:exclude.txt" Not working as intended.

### ISSUE THREAD

**Issue by spinzthewiz** [andrebrait/1g1r-romset-generator#36]
Tested on Windows 10, two different PCs.

When using --exclude-after "file:exclude-after.txt" or --exclude "file:exclude.txt" the list in the file is ignored, unless it is only one word. If the file contains one word, it works as intended. If it contains a comma separated list of words NONE of the words will be excluded.

Using --exclude-after "the,list,of,words" and --exclude "exclude,words"works as intended.

**Comment by andrebrait** [comment]
IIRC the file should be separated by line, not commas, so

```
this
and
that
```

**Comment by spinzthewiz** [comment]
That is absolutely working now thank you. I assumed the format would be the same as the default listing. Is this information located in the documentation and I just missed it?
