### ISSUE TITLE
Aftermarket Homebrew

### ISSUE THREAD

**Issue by westoncampbell** [andrebrait/1g1r-romset-generator#37]
No-Intro is now including **a lot** of "(Aftermarket) (Homebrew)" ROMs in their database.

Can these options be added to the filters? Maybe --no-homebrew? Using --exclude "(Homebrew)" for now.

Also, sometimes there are multiple versions of homebrew games.

For example, Nintendo Entertainment System:

Nova the Squirrel (World) (v1.01) (Aftermarket) (Homebrew).zip
Nova the Squirrel (World) (v1.02) (Aftermarket) (Homebrew).zip
Nova the Squirrel (World) (v1.03) (Aftermarket) (Homebrew).zip
Nova the Squirrel (World) (v1.04) (Aftermarket) (Homebrew).zip
Nova the Squirrel (World) (v1.05) (Aftermarket) (Homebrew).zip
Nova the Squirrel (World) (v1.06) (Aftermarket) (Homebrew).zip

Can the scanning be updated to only include the latest version number?

Currently it includes multiple version numbers in the output folder.

FYI -- I know you have the new DATRomTool project now, but I still prefer this project. Hopefully you'll be able to update it. :-)

One more idea -- It would be nice to have the option to use partial filenames for the dat files.

I currently have to rename the dat files every time I use this script. I have all my commands for each system saved to a text file.

Nintendo - Nintendo Entertainment System (Headerless) (Parent-Clone) (20220620-100820).dat

I would like to only include "Nintendo - Nintendo Entertainment System (Headerless)" in my text file command list, and the script would automatically detect the correct file.

This would allow me to download the latest dats from No-Intro and drop them in my input folder and use my saved commands without having to rename files to match my saved commands.

**Comment by andrebrait** [comment]
It's possible, yes. I just need some time to do it.

Alternatively, you can use exclusions to exclude these names from candidates. Let me know if that works and I can see if I can make a dedicated option for it. I'll also include it in DATROMTool if that's the case.

And what do you mean it outputs multiple version numbers? That shouldn't happen, unless the games are lacking parent-clone data and then the tool thinks they're different games.

Could you send me the DAT file you're using?

**Comment by westoncampbell** [comment]
I think you're correct about lacking parent-clone data. I don't think it happened for all homebrew -- just specific versions. I will verify this when I am home. Yes, the exclusion worked to remove all homebrew titles from my final output.
