### ISSUE TITLE
Virtual Console / Gamecube Edition filtering?

### ISSUE THREAD

**Issue by LiveFastCyYoung** [andrebrait/1g1r-romset-generator#4]
In the No-Intro NES set, there are Virtual Console re-releases and Gamecube Edition(I believe from Animal Crossing) re-releases. I couldn't find a way, outside of regex to filter these. Any consideration to making this a filter flag?

**Comment by andrebrait** [comment]
I have no current plans to add that, but adding `--exclude "Virtual Console,GameCube"` should be enough, without regexes. 

Maybe I will, but I don't want to make the number of options too big, I think.

**Comment by LiveFastCyYoung** [comment]
Oversight on my part with regards to using the exclude statement. That works!
