### ISSUE TITLE
--no-aftermarket and --no-homebrew not recognized

### ISSUE THREAD

**Issue by nilsbyte** [andrebrait/1g1r-romset-generator#40]
```
        --no-aftermarket        Filter out aftermarket ROMs
        --no-homebrew           Filter out homebrew ROMs
```

Are not recognized. They also do *NOT* work when using `--no-all`

**Comment by andrebrait** [comment]
Did you get the code from master or have you downloaded a release?

Those changes aren't yet released. They're only available on master.

**Comment by nilsbyte** [comment]
I downloaded the release 1.9.10 … thanks for clarifying. Why is there no new release?

**Comment by andrebrait** [comment]
I just haven't had the time to test it and create a release.

If you'd like to help with that, you can download master and use it instead. The instructions are the same, you just need to replace the files from the one you downloaded with the ones you get from GitHub when downloading the master branch.

**Comment by andrebrait** [comment]
Version 1.9.11 got released with these changes now applied.
Let me know if you still find anything wrong with it.

**Comment by nilsbyte** [comment]
@andrebrait thank you. I did not have the time to test it thoroughly, sorry. But I just wanted so say how awesome this project is. I built a batch file for exactly this purpose but it was inflexible. Thanks to you and your script I now can filter my roms as I like.
