### ISSUE TITLE
Regions and Languages reference guides

### ISSUE THREAD

**Issue by Xeretinha** [andrebrait/1g1r-romset-generator#41]
More a tip than a issue itself. Since the tool is totally commandline based, I just want to advice making a reference guide for regions **and** languages somewhere (the wiki would fit, but maybe also at --help option). I know that, at ReadMe's project, the language reference is pointed that No-Intro Naming Convention is used as basis - and then, they points on theyr wiki that _languages_ conventioning is based on ISO 639-1 CodeSets.
Okay... There's still lacking a region reference. Plus, would be better if finding the language reference "near" the tool pages, for non-familiarized coding users.

===========

PT-BR (since seems the coder uses the same native language than me)

===========

É mais uma sugestão que um problema. Uma vez que a ferramenta é totalmente baseada em linha de comando (com menos intuitividade que a possível em uma GUI), seria interessante que houvessem tabelas de referência tanto das Regiões quanto dos Idiomas possíveis para filtragem. Na wiki do projeto já seria suficiente, se disponível (também) na "ajuda" do próprio programa, tanto melhor.
Sei que na ReadMe do projeto é indicado, para o caso de idiomas, o uso da convenção de nomenclaturas do (scene group) No-Intro - que, por sua vez, explicam terem se baseado na ISO 693-1. Ainda assim falta uma tabela de referência de Regiões/Países disponíveis para filtragem (sei que isso varia de console para console, mas há ferramentas - como o ROMCenter e o ReTool - que já vêm com listas predefinidas); enquanto também seria boa ideia ter, de fácil acesso, a lista de idiomas mais próxima da ferramenta em si, de modo que usuários pouco familiarizados com "programação" em geral (usei "coding" lá em cima na intenção de generalizar tanto quem programa quanto quem lida com essas tabelas de padronização) não tenham que ficar garimpando pela internet e já encontrem todo o necessário próximo do download do gerador.

E aí? Tem jeito?

**Comment by andrebrait** [comment]
Ter jeito tem, mas eu estou um bocado ocupado ultimamente.
Se você quiser, rola de fazer um PR pra adicionar isso no README.

Eu estou parando de usar a Wiki. Muito chato de manter e sem registro de mudanças bom que nem o controle de versão do código em si.

**Comment by Xeretinha** [comment]
Pode ser no README sim, sem problemas! Provavelmente até melhor que na wiki, uma vez que a ReadMe já contém praticamente tudo o necessário para o uso do script, e ainda por cima poupa qualquer "navegação adicional" pra chegar na referência, estando disponível no mesmo lugar onde o (futuro) usuário chega para baixar a ferramenta! Sugeri a wiki, aliás, por ser o lugar tradicional para este tipo de coisa... 

Já quanto à disponibilidade, tu é o chefe, rapá! Até porque, se bem entendi, futuramente o gerador será substituído por uma ferramenta beeem mais potente (a DATROMTool, em Java ainda por cima!), e certamente é compreensível que seus esforços estejam focados nela. Arrisco dizer até que trazer o assunto à tona vai influenciar no resultado final da DRT, então cada coisa a seu tempo!

Gardecido pela atenção, cumpadi!

**Comment by andrebrait** [comment]
Nem é por causa do DATROMTool não. Ele ainda não está pronto, de qualquer forma. Eu não tenho tempo pra muita coisa em geral, incluindo o pobre coitado do DATROMTool.

Eu estava perguntando se você não gostaria de fazer a mudança você mesmo e submeter aqui como um Pull Request. Isso faria a mudança vir aqui pro repositório e ser incluída em futuros releases/aqui no README principal mesmo.

Eu estava te dando uma opção pra poder incluir esse guia de regiões no README sem ter que esperar eu ter tempo pra isso ;)

**Comment by Xeretinha** [comment]
Sei que não é (só) por causa da DATROMTool... Certamente você tem projetos profissionais - o cenário de emulação é mantido 99% em caráter hobbysta. Citei ele pois, neste contexto, ele deve ser prioridade bem maior que o romset generator, que, convenhamos, já está praticamente finalizado!

Vou ver o que consigo fazer para adicionar no README. Confesso que vim fazer a sugestão justamente por ter ficado meio perdido para usar estes dados na linha de comando, mas também por uma certa (sincericídio mode ON) "preguiça" de me aprofundar no assunto. Ao menos a lista de idiomas é fácil: basta que eu pegue a referência supracitada feita pelo pessoal do No-Intro.
Já a lista de regiões (que foi o que me deixou mais perdido) pode ser um pouco mais difícil - mas até pra isso já tenho um plano, que é fuxicar nos códigos de outras ROM Managers (especialmente a ROMCenter). Acho que próximo final de semana já consigo alguma coisa, mesmo tendo sido convocado para trabalhar nas eleições (atualmente sou agente de organização concursado em uma escola pública). Como sexta feira será ponto facultativo do Dia do Servidor, acho que já dê pra render algo antes mesmo de sabermos quem vai "governar" o HU3sil pelos próximos 4 anos! ;)

**Comment by Xeretinha** [comment]
Enviei a proposta de alteração do ReadMe.md

Confesso que deu um certo trabalho... Nem tanto encontrar as tais listas, mas sim concluir o que deveria ser incluso ou não - decidi me ater ao que está explícito na wiki do No-Intro, embora já tenha me deparado com algumas listas de região mais amplas e/ou complexas (como a de [1G1R do Yeti, linhas 16 a 64](https://gitlab.com/retrogaming1/no-intro_1g1r/-/blob/master/1G1R_No-Intro_Set.py)).

Outra coisa é que notei um certo conflito entre o que é dito na wiki do No-Intro e as possibilidades de argumentos descritos na sua ferramenta, que é a diferença entre nomes completos dos países e as abreviações de três letras. Expliquei que pode ser usada a abreviação, dado que a convenção anterior basicamente pega as três primeiras letras dos nomes dos países, mas receio que isso possa resultar nalgum erro.

Mas... Tá feito, chefe! Espero ter ajudado! ;)

**Comment by andrebrait** [comment]
Parece que ainda falta você abrir um pull request pra esse repositório aqui.

E você chegou também a ver [isso aqui](https://github.com/andrebrait/1g1r-romset-generator/blob/master/generate.py#L51) né?

**Comment by Xeretinha** [comment]
Pronto! Acho que agora acertei tudo - inclusive enviando o pull request para o repositório. My bad: não sou programador, e nunca tinha mexido com GitHub nesse nível, apenas tinha olhado as listas de issue pra procurar soluções ou, se muito, me manifestar a respeito de algum problema (meio como um fórum mesmo)...

E... Confesso que não tinha encontrado essa parte do generate.py também: pesquisei por "regions", "languages" e coisas assim no repositório pra ver se sanava minha dúvida antes de fazer a sugestão desse issue/tópico, mas não encontrava nada (por isso aliás que resolvi criar o issue)! Vai se entender...

O bom é que acabei aprendendo mais umas coisas e ajudando de quebra! ;P
