### ISSUE TITLE
"Latest Revision" in scoring system not working?

### ISSUE THREAD

**Issue by LiveFastCyYoung** [andrebrait/1g1r-romset-generator#5]
When running the script on a No-Intro NES set, I am getting all revisions of a game.

This is the syntax I am using to create a set...

python3 generate.py -r USA -e zip -i "c:\nes" -o "c:\nes_fix" -d "Nintendo - Nintendo Entertainment System (20200127-000518).dat" --no-all

Using this, I still end up with original rom and their Rev 1 equivalent.

**Comment by andrebrait** [comment]
Any specific examples so I can look into it faster?

**Comment by andrebrait** [comment]
From the file name you used, I'm wondering if this is a Parent/Clone XML or a Standard DAT.

You need to grab the Parent/Clone XML from the No-Intro DAT-o-matic instead of a standard DAT for this to work.

**Comment by LiveFastCyYoung** [comment]
Sure enough, I had the wrong DAT file.

Thanks for the help and the excellent tool!

**Comment by andrebrait** [comment]
@LiveFastCyYoung no problem :-)

There's an issue I'm facing with games that span multiple ROMs, and I'll fix it today. If you can, please wait until version 1.0.4 is out to use it
